name: Update YouTube Playlist

on:
  schedule:
    - cron: '0 */3 * * *' # Runs every 3 hours
  workflow_dispatch:      # Allows manual run from Actions tab

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install yt-dlp
        run: |
          pip install -r requirements.txt

      - name: Run nkyt Script
        run: python nkyt.py

      - name: Commit and Push changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add playlist.m3u
          # Only commit if the playlist actually changed
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update Playlist" && git push)
